version: "3.4"

services:
  create_clients:
    build:
      context: .
    image: app-spring-clients-list:v1
    container_name: spring_create_clients
    hostname: spring_create_clients
    command: bash container/inst.sh
    environment:
      - LEVEL=dev
      - POSTGRES_USER=clients
      - POSTGRES_PASSWORD=clients
      - POSTGRES_DB=clients
    ports:
      - 5499:5432
    volumes:
      - ./:/app

